import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7F6',
  },
  content: {
    paddingBottom: 30,
  },
  header: {
    height: 170,
    justifyContent: 'center',
    paddingTop: 50,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 35,
    borderBottomRightRadius: 35,
  },
  title: {
    color: '#fff',
    fontSize: 30,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  subtitle: {
    color: '#D4F1EF',
    marginTop: 8,
    fontSize: 14,
  },
  formCard: {
    marginTop: 10,
    marginHorizontal: 20,
    backgroundColor: '#ffffff',
    borderRadius: 25,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  savedMedicationCard: {
    marginTop: 24,
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: '#ffffff',
    borderRadius: 25,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  medicationList: {
    marginBottom: 16,
  },
  medicationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    marginRight: 8,
  },
  medicationItemButton: {
    flex: 1,
    backgroundColor: '#F5F7F6',
    borderRadius: 15,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#D7E4E1',
  },
  medicationItemButtonActive: {
    backgroundColor: '#D4F1EF',
    borderColor: '#1B5E5A',
  },
  medicationItemName: {
    color: '#235347',
    fontWeight: '700',
    fontSize: 14,
  },
  medicationItemSubtext: {
    color: '#7A9996',
    fontSize: 12,
    marginTop: 4,
  },
  medicationDeleteBtn: {
    backgroundColor: '#B00020',
    borderRadius: 12,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  medicationDeleteText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
  },
  newMedicationBtn: {
    marginTop: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#E6FFFA',
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#1B5E5A',
    borderStyle: 'dashed',
  },
  newMedicationText: {
    color: '#1B5E5A',
    fontWeight: '700',
  },
  label: {
    color: '#235347',
    fontWeight: '700',
    marginTop: 16,
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#F5F7F6',
    borderRadius: 15,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: '#2A3B38',
  },
  button: {
    marginTop: 24,
    backgroundColor: '#1B5E5A',
    borderRadius: 15,
    paddingVertical: 14,
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timeInput: {
    flex: 1,
    marginRight: 10,
  },
  addTimeButton: {
    backgroundColor: '#1B5E5A',
    borderRadius: 15,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addTimeButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  timesList: {
    marginTop: 12,
    backgroundColor: '#F5F7F6',
    borderRadius: 15,
    padding: 12,
  },
  timeItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#D7E4E1',
  },
  timeText: {
    color: '#235347',
    fontSize: 15,
    fontWeight: '600',
  },
  removeTimeText: {
    color: '#B00020',
    fontWeight: '700',
  },
  secondaryButton: {
    marginTop: 12,
    borderRadius: 15,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#1B5E5A',
  },
  secondaryButtonText: {
    color: '#1B5E5A',
    fontWeight: '700',
    fontSize: 16,
  },
  testButton: {
    marginTop: 12,
    borderRadius: 15,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: '#E6FFFA',
  },
  testButtonText: {
    color: '#235347',
    fontWeight: '700',
    fontSize: 16,
  },
  deleteButton: {
    marginTop: 12,
    borderRadius: 15,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: '#B00020',
  },
  deleteButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  infoBox: {
    marginTop: 24,
    backgroundColor: '#EAF7F4',
    borderRadius: 20,
    padding: 16,
  },
  infoTitle: {
    fontWeight: '700',
    color: '#1B5E5A',
    marginBottom: 8,
  },
  infoText: {
    color: '#235347',
    fontSize: 14,
    marginTop: 4,
  },
});
